DROP TABLE CYUSER PURGE;
DROP TABLE CYMEMBER PURGE;
DROP TABLE CYPICTURE PURGE;
DROP TABLE CYINTRO PURGE;
DROP TABLE CYMEMBERBOARD PURGE;
DROP TABLE CYPICREPLE PURGE;
DROP TABLE CYGUESTREPLE PURGE;
DROP TABLE CYGUESTBOOK PURGE;
DROP TABLE CYMYITEM PURGE;
DROP TABLE CYCART PURGE;
DROP TABLE CYITEMSHOP PURGE;
DROP TABLE CYMENU PURGE;
DROP TABLE CYBOARD PURGE;
DROP TABLE CYFPROFILE PURGE;
DROP TABLE CYPICTUREBOARD PURGE;
DROP TABLE CYUSINGBG PURGE;
DROP TABLE CYUSINGMINIMI PURGE;
DROP TABLE CYMEMBERLIST PURGE;
DROP TABLE CYBOARDMENU PURGE;
DROP TABLE CYBOARDREPLE PURGE;
DROP TABLE CYUSINGSONGS PURGE;
DROP TABLE CYUSINGSTORYROOM PURGE;
DROP TABLE CYVIDEO PURGE;
DROP TABLE CYVIDEOREPLE PURGE;
DROP TABLE CYVIDEOBOARD PURGE;
DROP TABLE PRESENT PURGE;
DROP TABLE PROFILE PURGE;
DROP TABLE CYUSINGFONT PURGE;

COMMIT;

--1.회원정보
CREATE TABLE CYUSER(
USERID VARCHAR2(18) PRIMARY KEY,
USERPW VARCHAR2(18),
USERNAME VARCHAR2(10),
USERGENDER VARCHAR2(4),
USERDOTORY NUMBER,
USERBIRTH DATE,
TODAY NUMBER,
TOTALDAY NUMBER,
CHECKDAY DATE,
PRESENTLIST NUMBER);

--2.유저간 일촌관리
CREATE TABLE CYMEMBER(
USERID1 VARCHAR2(18),
USERVALUE1 VARCHAR2(10),
USERID2 VARCHAR2(18),
USERVALUE2 VARCHAR2(10));

--3.사진
CREATE TABLE CYPICTURE(
NUM NUMBER,
SUBJECT VARCHAR2(30),
USERID VARCHAR2(18),
FOLDERNAME VARCHAR2(30),
USERNAME VARCHAR2(10),
CONTENT VARCHAR2(4000),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
SCRAP NUMBER,
OWNER VARCHAR2(18),
ORIGINALPICNUM NUMBER,
CREATED DATE);

SELECT * FROM CYPICTURE;

--4. 타이틀
CREATE TABLE CYINTRO(
USERID VARCHAR2(18) PRIMARY KEY,
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
INTRO VARCHAR2(1000),
TODAY VARCHAR2(10),
TITLE VARCHAR2(30));

--5.일촌평
CREATE TABLE CYMEMBERBOARD(
USERID VARCHAR2(18),
MEMBERID VARCHAR2(18),
MEMBERNAME VARCHAR2(10),
MEMBERVALUE VARCHAR2(10),
CONTENT VARCHAR2(100),
CREATED DATE);

--6. 사진첩뎃글
CREATE TABLE CYPICREPLE(
NUM NUMBER,
PICNUM NUMBER,
USERID VARCHAR2(18),
USERNAME VARCHAR2(10),
REPLIERID VARCHAR2(18),
REPLIERNAME VARCHAR2(10),
GROUPNUM NUMBER,
ORDERNUM NUMBER,
CONTENT VARCHAR2(1000));

--7. 방명록뎃글
CREATE TABLE CYGUESTREPLE(
NUM NUMBER PRIMARY KEY,
GUESTNUM NUMBER,
USERID VARCHAR2(18),
USERNAME VARCHAR2(10),
CONTENT VARCHAR2(1000),
CREATED DATE);

--8. 방명록
CREATE TABLE CYGUESTBOOK(
NUM NUMBER PRIMARY KEY,
USERID VARCHAR2(18),
MEMBERID VARCHAR2(18),
MEMBERVALUE VARCHAR2(10),
MEMBERNAME VARCHAR2(10),
CONTENT VARCHAR2(4000),
CREATED DATE,
SECRET NUMBER);

--9. 상품구매목록
CREATE TABLE CYMYITEM(
USERID VARCHAR2(18),
TYPE VARCHAR2(30),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
BUYDATE DATE,
NUM NUMBER,
BUYER VARCHAR2(18)
);

--9-1  쇼핑카트
CREATE TABLE CYCART(
USERID VARCHAR2(18) NOT NULL,
ITEMNAME VARCHAR2(100),
ITEMPRICE NUMBER,
TYPE VARCHAR2(30),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
NUM NUMBER
);

--10. 마켓상품리스트
CREATE TABLE CYITEMSHOP(
NUM NUMBER PRIMARY KEY,
ITEMNAME VARCHAR2(100),
TYPE VARCHAR2(30),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
ITEMPRICE NUMBER DEFAULT 10);

--11.메뉴버튼
CREATE TABLE CYMENU(
USERID VARCHAR2(18) PRIMARY KEY,
MENU1 CHAR(1) CONSTRAINT boolean_menu1_ck CHECK(MENU1 IN ('0','1')),
MENU2 CHAR(1) CONSTRAINT boolean_menu2_ck CHECK(MENU2 IN ('0','1')),
MENU3 CHAR(1) CONSTRAINT boolean_menu3_ck CHECK(MENU3 IN ('0','1')),
MENU4 CHAR(1) CONSTRAINT boolean_menu4_ck CHECK(MENU4 IN ('0','1')),
MENU5 CHAR(1) CONSTRAINT boolean_menu5_ck CHECK(MENU5 IN ('0','1')),
MENU6 CHAR(1) CONSTRAINT boolean_menu6_ck CHECK(MENU6 IN ('0','1')),
MENU7 CHAR(1) CONSTRAINT boolean_menu7_ck CHECK(MENU7 IN ('0','1')),
MENUBACKGROUNDCOLOR VARCHAR2(8),
MENUFONTCOLOR VARCHAR2(8),
MENUBORDERCOLOR VARCHAR2(8)
);

--12.게시판
CREATE TABLE CYBOARD(
NUM NUMBER PRIMARY KEY,
USERID VARCHAR2(18),
USERNAME VARCHAR2(18),
SUBJECT VARCHAR2(30),
FOLDERNAME VARCHAR2(30),
CONTENT VARCHAR2(1000),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
CREATED DATE,
HITCOUNT NUMBER,
ORIGINALNUM NUMBER
);

--12-1.게시판 폴더메뉴
CREATE TABLE CYBOARDMENU(
NUM NUMBER PRIMARY KEY,
USERID VARCHAR2(18),
FOLDERNAME VARCHAR2(30),
TYPE NUMBER
);

--12-2. 게시판 뎃글
CREATE TABLE CYBOARDREPLE(
NUM NUMBER PRIMARY KEY,
GUESTNUM NUMBER,
USERID VARCHAR2(18),
USERNAME VARCHAR2(10),
CONTENT VARCHAR2(1000),
CREATED DATE);

--12-3.프로필
CREATE TABLE CYFPROFILE(
USERID VARCHAR2(18) PRIMARY KEY,
CONTENT VARCHAR2(1000)
);

--13. 사진첩 왼쪽 메뉴
CREATE TABLE CYPICTUREBOARD(
USERID VARCHAR2(18),
GROUPNAME VARCHAR2(30),
GROUPORDER NUMBER,
FOLDERNAME VARCHAR2(30),
FOLDERORDER NUMBER,
PRIVACY NUMBER CONSTRAINT CYPICTUREBOARD_PRIVACY_CK CHECK(PRIVACY IN ('0','1','2')));
-- 0 : 비공개 / 1 : 일촌공개 / 2 : 전체공개

--14. 일촌 신청 리스트
CREATE TABLE CYMEMBERLIST (
USERID1 VARCHAR2(18),
USERNAME1 VARCHAR2(10),
USERVALUE1 VARCHAR2(10),
USERID2 VARCHAR2(18),
USERNAME2 VARCHAR2(10),
USERVALUE2 VARCHAR2(10),
CREATED DATE,
USERMESSEGE VARCHAR2(1000),
TYPE NUMBER
);

--15. 사용하는배경
CREATE TABLE CYUSINGBG(
USERID VARCHAR2(18) PRIMARY KEY,
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100)
);

--16. 사용하는미니미
CREATE TABLE CYUSINGMINIMI(
USERID VARCHAR2(18) PRIMARY KEY,
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
IMGX VARCHAR2(5),
IMGY VARCHAR2(5)
);

--17. 사용하는음악
CREATE TABLE CYUSINGSONGS(
USERID VARCHAR2(18),
SONGORDER NUMBER,
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100)
);

--18. 사용하는스토리룸
CREATE TABLE CYUSINGSTORYROOM(
USERID VARCHAR2(18),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100)
);

--19. 동영상
CREATE TABLE CYVIDEO(
NUM NUMBER,
SUBJECT VARCHAR2(30),
USERID VARCHAR2(18),
FOLDERNAME VARCHAR2(30),
USERNAME VARCHAR2(10),
CONTENT VARCHAR2(4000),
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100),
SCRAP NUMBER,
OWNER VARCHAR2(18),
ORIGINALVIDEONUM NUMBER,
CREATED DATE);

--20. 동영상 댓글
CREATE TABLE CYVIDEOREPLE(
NUM NUMBER,
VIDEONUM NUMBER,
USERID VARCHAR2(18),
USERNAME VARCHAR2(10),
REPLIERID VARCHAR2(18),
REPLIERNAME VARCHAR2(10),
GROUPNUM NUMBER,
ORDERNUM NUMBER,
CONTENT VARCHAR2(1000));

-- -21. 동영상 왼쪽 메뉴
CREATE TABLE CYVIDEOBOARD(
USERID VARCHAR2(18),
GROUPNAME VARCHAR2(30),
GROUPORDER NUMBER,
FOLDERNAME VARCHAR2(30),
FOLDERORDER NUMBER,
PRIVACY NUMBER CONSTRAINT CYVIDEOBOARD_PRIVACY_CK CHECK(PRIVACY IN ('0','1','2')));
-- 0 : 비공개 / 1 : 일촌공개 / 2 : 전체공개

--22. 선물리스트
create table present(
userId varchar(18),
presentNum number);

-- 23. 사용하는 글꼴
CREATE TABLE CYUSINGFONT(
USERID VARCHAR2(18) PRIMARY KEY,
SAVEFILENAME VARCHAR2(100),
ORIGINALFILENAME VARCHAR2(100)
);

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
초기화

delete cyuser;
delete cymember;
delete cypicture;
delete cyintro;
delete cymemberboard;
delete cypicreple;
delete cyguestreple;
delete cyguestbook;
delete cymyitem;
delete cyitemshop;
delete cymenu;
delete cyboard;
delete cyfprofile;
delete cypictureboard;
delete cymemberlist;
delete cyusingbg;
delete cyusingminimi;
delete cyboardmenu;
delete cyboardreple;
delete cyusingsongs;
delete cyusingstoryroom;
delete cyvideoboard;
delete cyvideoreple;
delete cyvideo;
delete cyprofile;
delete cyusingfont;
commit;
---------------------------------------------------------------------------------------------------------
